remote_theme: andrewbanchich/spectral-jekyll-theme
title: Escapeling
description: Documentation for the study project 'Adaptive Language Learning' at Universität Osnabrück
tiles-source: posts
tiles-count: 4
